<html lang="en">
<head>
    <title>Add new Infrastructure</title>
    <!-- bootstrap-->
    <link rel="stylesheet" href="../Bootstrap/css/bootstrap.css">
    <!-- javascript -->
    <script type="text/javascript" src="../JS/javascript.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="../img/icon.png"/>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col mt-3">

        </div>
        <div class="col-6 mt-3 text-center">
            <h1>Add new Infrastructure</h1>
            <form  action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
                <input type="text" class="form-control" name="name" placeholder="Name*" required><br>
                <input type="text" class="form-control" name="postcode" placeholder="Postcode*" required><br>
                <select name="type" class="form-control">
                    <option value="Road">Road</option>
                    <option value="Rail">Rail</option>
                    <option value="Airport">Airport</option>
                    <option value="Port">Port</option>
                </select><br>
                <select name="classification" class="form-control">
                    <option value="Critical">Critical</option>
                    <option value="Major">Major</option>
                    <option value="Minor">Minor</option>
                </select><br>
                <input type="submit" class="btn btn-dark" name="submit" value="Submit" required><br>
            </form>
        </div>
        <div class="col mt-3"></div>
    </div>
</div>
</body>
</html>