<html lang="en">
<head>
    <title>Add new Demographics</title>
    <!-- bootstrap-->
    <link rel="stylesheet" href="../Bootstrap/css/bootstrap.css">
    <!-- javascript -->
    <script type="text/javascript" src="../JS/javascript.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="../img/icon.png"/>
</head>
<body>


<div class="container">
    <div class="row">
        <div class="col mt-3">

        </div>
        <div class="col-6 mt-3 text-center">
            <h1>Add new Demographics</h1>
            <form  action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
                <input type="text" class="form-control" name="postcode" placeholder="Postcode*" required><br>
                <input type="number" class="form-control" name="totalPopulation" placeholder="Total Population*" required><br>
                <input type="number" class="form-control" name="totalElderly" placeholder="Total Elderly*" required><br>
                <input type="number" class="form-control" name="totalMobilityNeeds" placeholder="Total mobility needs*" required><br>
                <input type="number" class="form-control" name="totalHealthNeeds" placeholder="Total health needs*" required><br>
                <input type="submit" class="btn btn-dark" name="submit" value="Submit" required><br>
            </form>
        </div>
        <div class="col mt-3"></div>
    </div>
</div>
</body>
</html>