<!DOCTYPE html>
<html lang="en">

<head>
    <title>Buildings</title>
    <meta charset="utf-8">
    <meta name="description" content="Bootstrap.">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="../Bootstrap/css/bootstrap.css">
    <script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container">
    <div class="row">
        <div class="col text-center">
            <h1 class="display-4 text-center mt-2">Buildings</h1><br>
            <button class="btn btn-dark mb-2" onclick="redirectToAddNewBuilding()">Add new building</button>
        </div>
    </div>
</div>
<table id="myTable" class="table">
    <thead>
        <tr>
            <th scope="col" data-field="ID" data-sortable="true">ID</th>
            <th scope="col" data-field="Name" data-sortable="true">Name</th>
            <th scope="col" data-field="Type" data-sortable="true">Type</th>
            <th scope="col" data-field="Postcode" data-sortable="true">Postcode</th>
            <th scope="col" data-field="City" data-sortable="true">City</th>
            <th scope="col" data-field="Size" data-sortable="true">Size m2</th>
            <th scope="col" data-field="maxOccupants" data-sortable="true">Max Occupants</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    <?php for ($i = 0; $i < count($buildingsData); $i++) { ?>
        <tr id="tr-id-2" class="tr-class-2">
            <td><?php echo $buildingsData[$i]['_id'] ?></td>
            <td><?php echo $buildingsData[$i]['name'] ?></td>
            <td><?php echo $buildingsData[$i]['type'] ?></td>
            <td><?php echo $buildingsData[$i]['postcode'] ?></td>
            <td><?php echo $buildingsData[$i]['city'] ?></td>
            <td><?php echo $buildingsData[$i]['size_m2'] ?></td>
            <td><?php echo $buildingsData[$i]['maxOccupants'] ?></td>
            <td><a href="../Controllers/deleteItem.php?buildingId=<?php echo $buildingsData[$i]['_id']?>"><img src="../img/delete.png" height="20px" width="20px" alt=""></a></td>
        </tr>
    <?php } ?>
    </tbody>
</table>

</body>

<script>
    $(document).ready(function () {
        $('#myTable').dataTable();
    });
</script>

</html>