<html>

<head>
    <title>Home Page</title>
    <!-- css -->
    <link rel="stylesheet" href="../CSS/index.css">
    <!-- bootstrap-->
    <link rel="stylesheet" href="../Bootstrap/css/bootstrap.css">
    <!-- javascript -->
    <script type="text/javascript" src="../JS/javascript.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="../img/icon.png"/>
</head>

<script>

</script>

<body>

<div class="container">
    <div id="slideshow">
        <div class="elemnt"></div>
        <div class="elemnt1"></div>
        <div class="elemnt2"></div>
        <div class="elemnt3"></div>
    </div>
</div>

</body>

</html>