<html lang="en">

<head>
    <title>Infrastructure</title>
    <meta charset="utf-8">
    <meta name="description" content="Bootstrap.">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="../Bootstrap/css/bootstrap.css">
    <script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container">
    <div class="row">
        <div class="col text-center">
            <h1 class="display-4 text-center mt-2">Infrastructure</h1><br>
            <button class="btn btn-dark mb-2" onclick="redirectToAddNewInfrastructure()">Add new infrastructure</button>
        </div>
    </div>
</div>
<table id="myTable" class="table">
    <thead>
    <tr>
        <th scope="col" data-field="ID" data-sortable="true">ID</th>
        <th scope="col" data-field="Type" data-sortable="true">Type</th>
        <th scope="col" data-field="Name" data-sortable="true">Name</th>
        <th scope="col" data-field="Classification" data-sortable="true">Classification</th>
        <th scope="col" data-field="Postcode" data-sortable="true">Postcode</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <?php
    for ($i = 0; $i < count($infrastructureData); $i++) {
        ?>
        <tr id="tr-id-2" class="tr-class-2">
            <td><?php echo $infrastructureData[$i]['_id'] ?></td>
            <td><?php echo $infrastructureData[$i]['type'] ?></td>
            <td><?php echo $infrastructureData[$i]['name'] ?></td>
            <td><?php echo $infrastructureData[$i]['classification'] ?></td>
            <td><?php for ($j = 0; $j < count($infrastructureData[$i]['postcodes']); $j++ ) {
                    echo "'".$infrastructureData[$i]['postcodes'][$j]."' ";
                } ?>
            </td>
            <td><a href="../Controllers/deleteItem.php?infrastructureId=<?php echo $infrastructureData[$i]['_id']?>"><img src="../img/delete.png" height="20px" width="20px" alt=""></a></td>
        </tr>
        <?php
    }
    ?>
    </tbody>
</table>

</body>

<script>
    $(document).ready(function () {
        $('#myTable').dataTable();
    });
</script>

</html>